### ISSUE TITLE
'undefined' becomes 'null' after deserialization

### ISSUE THREAD

**Issue by petermasking** [MaskingTechnology/jitar#500]
This behavior is found when (de)serializing a class object. In this specific case, undefined values are getting replaced with null values in the constructor arguments. We need to figure out the cause and the range of this issue.

**Comment by basmasking** [comment]
The issue here is that the value of `undefined`, when included in an array, is changed into `null`. This is done to presevere the length of the array by the stringify method.

To overcome this issue, we need to take a slightly different approach and cannot simply use the existing array serialization.
